let nuvem1 = document.getElementById('nuvem1')
let nuvem2 = document.getElementById('nuvem2')
let nuvem3 = document.getElementById('nuvem3')
let nuvem4 = document.getElementById('nuvem4')
let nuvem5 = document.getElementById('nuvem5')
let nuvem6 = document.getElementById('nuvem6')

let concha1 = document.getElementById('concha1')
let concha2 = document.getElementById('concha2')
let concha3 = document.getElementById('concha3')
let concha4 = document.getElementById('concha4')
let concha5 = document.getElementById('concha5')
let concha6 = document.getElementById('concha6')

let fogo1 = document.getElementById('fogo1')
let fogo2 = document.getElementById('fogo2')
let fogo3 = document.getElementById('fogo3')
let fogo4 = document.getElementById('fogo4')
let fogo5 = document.getElementById('fogo5')
let fogo6 = document.getElementById('fogo6')

let pedra1 = document.getElementById('pedra1')
let pedra2 = document.getElementById('pedra2')
let pedra3 = document.getElementById('pedra3')
let pedra4 = document.getElementById('pedra4')
let pedra5 = document.getElementById('pedra5')
let pedra6 = document.getElementById('pedra6')

let borboleta1 = document.getElementById('borboleta1')
let borboleta2 = document.getElementById('borboleta2')
let borboleta3 = document.getElementById('borboleta3')
let borboleta4 = document.getElementById('borboleta4')
let borboleta5 = document.getElementById('borboleta5')
let borboleta6 = document.getElementById('borboleta6')

let flor1 = document.getElementById('flor1')
let flor2 = document.getElementById('flor2')
let flor3 = document.getElementById('flor3')
let flor4 = document.getElementById('flor4')
let flor5 = document.getElementById('flor5')
let flor6 = document.getElementById('flor6')

function addLocal(nome, item) {
    localStorage.setItem(item, nome)
}

nuvem1.addEventListener("click", function(){addLocal("nuvem1", "item1")})
nuvem2.addEventListener("click", function(){addLocal("nuvem2", "item2")})
nuvem3.addEventListener("click", function(){addLocal("nuvem3", "item3")})
nuvem4.addEventListener("click", function(){addLocal("nuvem4", "item4")})
nuvem5.addEventListener("click", function(){addLocal("nuvem5", "item5")})
nuvem6.addEventListener("click", function(){addLocal("nuvem6", "item6")})

concha1.addEventListener("click", function(){addLocal("concha1", "item7")})
concha2.addEventListener("click", function(){addLocal("concha2", "item8")})
concha3.addEventListener("click", function(){addLocal("concha3", "item9")})
concha4.addEventListener("click", function(){addLocal("concha4", "item10")})
concha5.addEventListener("click", function(){addLocal("concha5", "item11")})
concha6.addEventListener("click", function(){addLocal("concha6", "item12")})

fogo1.addEventListener("click", function(){addLocal("fogo1", "item13")})
fogo2.addEventListener("click", function(){addLocal("fogo2", "item14")})
fogo3.addEventListener("click", function(){addLocal("fogo3", "item15")})
fogo4.addEventListener("click", function(){addLocal("fogo4", "item16")})
fogo5.addEventListener("click", function(){addLocal("fogo5", "item17")})
fogo6.addEventListener("click", function(){addLocal("fogo6", "item18")})

pedra1.addEventListener("click", function(){addLocal("pedra1", "item19")})
pedra2.addEventListener("click", function(){addLocal("pedra2", "item20")})
pedra3.addEventListener("click", function(){addLocal("pedra3", "item21")})
pedra4.addEventListener("click", function(){addLocal("pedra4", "item22")})
pedra5.addEventListener("click", function(){addLocal("pedra5", "item23")})
pedra6.addEventListener("click", function(){addLocal("pedra6", "item24")})

borboleta1.addEventListener("click", function(){addLocal("borboleta1", "item25")})
borboleta2.addEventListener("click", function(){addLocal("borboleta2", "item26")})
borboleta3.addEventListener("click", function(){addLocal("borboleta3", "item27")})
borboleta4.addEventListener("click", function(){addLocal("borboleta4", "item28")})
borboleta5.addEventListener("click", function(){addLocal("borboleta5", "item29")})
borboleta6.addEventListener("click", function(){addLocal("borboleta6", "item30")})

flor1.addEventListener("click", function(){addLocal("flor1", "item31")})
flor2.addEventListener("click", function(){addLocal("flor2", "item32")})
flor3.addEventListener("click", function(){addLocal("flor3", "item33")})
flor4.addEventListener("click", function(){addLocal("flor4", "item34")})
flor5.addEventListener("click", function(){addLocal("flor5", "item35")})
flor6.addEventListener("click", function(){addLocal("flor6", "item36")})

